#PBS -S /bin/bash
#PBS -q cmb
#PBS -l nodes=1:sl230s:ppn=16
#PBS -l walltime=240:00:00
#PBS -l mem=60000mb
#PBS -l vmem=60000mb
#PBS -l pmem=3750mb

source /usr/usc/python/2.7.8/setup.sh

cd $PBS_O_WORKDIR

OUTBASE="bground_sim_long_run$RANDOM"

time ./background-sim.py -t 15 -T 60000 -N 100 -w 10 -L 25e6 -l 1000 -m 4e-3 -u 5e-3 -r 2.5e-8 -a .23 -b 5.34 -o ${OUTBASE}.recomb -g ${OUTBASE}.simupop.log -s ${OUTBASE}.selloci

exit

