setwd("~/Documents/Drosophila/Chr3L")
a<-read.table("pairwise_distance_between_win_103_Chr3L")
a <- as.matrix(a)
b<-read.table("neibors_win103_Chr3L.txt")
fit1<-cmdscale(a,eig=TRUE, k=1)
windows=rownames(a) 
windows=as.numeric(windows) 
coordinate1<- fit1$points[,1]
coordinate1=as.matrix(coordinate1)
row.names(coordinate1)=rownames(a)
pdf(file="MDS_1D_103_Chr3L_colored_peaks.pdf")
plot(windows,coordinate1,xlab="windows_chr3L", main="MDS_1D_Chr3L")
points(c(b[,3]),coordinate1[as.character(c(b[,3])),1],col="blue",pch=15)
points(c(b[,2]),coordinate1[as.character(c(b[,2])),1],col="green",pch=17)
points(c(b[,1]),coordinate1[as.character(c(b[,1])),1],col="red",pch=19)
dev.off()
