#PBS -S /bin/bash
#PBS -q cmb
#PBS -l nodes=1:ppn=4
#PBS -l walltime=200:00:00
#PBS -l mem=64000mb
#PBS -l vmem=64000mb
#PBS -l pmem=16000mb

# for msprime
source /usr/usc/hdf5/1.8.12/setup.sh
# apparently pyvcf uses rpy
source ~/cmb/bin/R-setup-usc.sh 

source $HOME/cmb/bin/python3_setup.sh

cd $PBS_O_WORKDIR

for N in 500 1000 2000;
do
    for L in 5e7 7e7 8e7 10e7;
    do
        X="test_mN4_${L}_${N}_"
        SEED=$(printf "%06d" $RANDOM); 
        mkdir ${X}$SEED; 
        (/usr/bin/time --format='elapsed: %E / kernel: %S / user: %U / mem: %M' \
        ./msp-sim.py -n 1 -k 2000 -w 10 -N $N -o ${X}$SEED -d $SEED -u 0.0 -j 1\
            -m .001 -L $L \
            | grep -v REJECTING ) &> ${X}$SEED/run.log  &
    done
done

wait
